### ISSUE TITLE
Realizar ajuste na estrutura do Repositório

### ISSUE THREAD

**Issue by lucascorreaa** [FelipeTMedina/Portf-lio#6]
Captura para a base:

![image](https://github.com/FelipeTMedina/Portf-lio/assets/91700610/ad175cc6-42c4-4902-bdab-b2aa17fdbad3)

Como boa prática sempre descrever a imagem, utilizar kebab ou camelCase:

loginIcon.svg
profile-icon.svg

**Comment by FelipeTMedina** [comment]
Descrição adicionada a  imgs do portifólio e ajustado a estrutura do portifólio

**Comment by lucascorreaa** [comment]
feito!
